# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ✅ 상수
APP_NAME = "JYP-iOS"
SCHEME = "JYP-iOS"
BUNDLE_ID = "com.jyp.journeypiki"

default_platform(:ios)

platform :ios do
  # ✅ 새로운 인증서 생성

  # 테스트 플라이트 업로드
  desc "Push to TestFlight"
  lane :tf do |options|
    xcversion(version: "14.2.0")

    # ✅ 앱스토어 커넥트 키 연결
    app_store_connect_api_key(is_key_content_base64: true, in_house: false)

    get_certificates

    get_provisioning_profile(
      force: true,
      filename: "JYP-iOS.Release.mobileprovision",
    )


    # ✅ 빌드 넘버 증가
    increment_build_number({ build_number: latest_testflight_build_number() + 1 })

    # ✅ 빌드
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
      export_method: "app-store",
    )

    # ✅ 테스트 플라이트 업로드
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
